[tool.pyright]
reportOptionalMemberAccess = false
reportArgumentType = false
reportUnknownParameterType = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportAny = false
reportUnusedCallResult = false
